# -*- coding: utf-8 -*-
"""matplot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OIqErZEH1OP1Ca8YHsvE6fY6twLIxVYg
"""

import matplotlib.pyplot as plt

import numpy as np

x = np.array([0,3.14/4, 3.14/2,3.14, (3.14/2)+3.14, (2*3.14)])

print(x)

y = np.sin(x)

print((y))





# make data



# plot
fig, ax = plt.subplots()

ax.plot(x, y, linewidth=2.0)

ax.set(xlim=(0, 50), xticks=np.arange(0, 20),
       ylim=(-2, 2), yticks=np.arange(-2, 2))

plt.show()